Select * from customer

--Q1. What is the total revenue generated by male vs. female customers?
	Select gender, sum(purchase_amount)as Total_revenue
	From customer
	Group By gender
	Order By total_revenue DESC;
	
--Q2. Which customers used a discount but still spent more than the average purchase amount? 
	Select customer_id, purchase_amount From customer
	Where discount_applied = 'Yes' and 
		  purchase_amount > (Select AVG(purchase_amount) From customer)
		  
--Q3. Which are the top 5 products with the highest average review rating?
	Select item_purchased as products, Round(AVG(review_rating)::Numeric,2) as avg_review_rating
	From customer
	Group By item_purchased
	Order By avg_review_rating DESC
	Limit 5;
	
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
	Select shipping_type, Round(AVG(purchase_amount),2) as avg_purchase_amt
	From customer
	Where shipping_type in ('Standard','Express')
	Group By shipping_type;
	
--Q5. Do subscribed customers spend more? Compare average spend and 
--    total revenue between subscribers and non-subscribers.
	Select subscription_status,
		   Round(AVG(purchase_amount),2) as avg_spend,
		   Round(Sum(purchase_amount),2) as Total_revenue
	From customer
	Group By subscription_status
	Order By 2,3 Desc;
	
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
	Select item_purchased ,
		  Round(AVG(Case When discount_applied = 'Yes' Then 1 Else 0 End)*100,2) as Discount_percentage
	From customer
	Group By item_purchased
	Order By Discount_percentage DESC
	Limit 5;
	
--Q7. Segment customers into New, Returning, and Loyal based on their total 
--    number of previous purchases, and show the count of each segment. 
	with customer_type as (
		Select customer_id, previous_purchases,
		Case
			When previous_purchases = 1 Then 'New'
			When previous_purchases Between 2 and 10 Then 'Returning'
			Else 'Loyal'
		End as customer_segment
		From customer
	)
	Select customer_segment, count(*) as No_of_customer
	From customer_type
    Group By customer_segment
	Order By no_of_customer DESC;
	
--Q8. What are the top 3 most purchased products within each category
	With item_count as (
		Select category, item_purchased,
			   Count(customer_id) as Total_orders,
			   Row_Number() Over(partition By category Order By Count(customer_id) DESC) as item_rank
		From customer
		Group By category, item_purchased
	)
	Select item_rank, category, item_purchased, total_orders
	From item_count
	where item_rank <=3
	
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
	Select subscription_status, count(customer_id) as repeat_buyer
	From customer
	Where previous_purchases >5
	Group By subscription_status
	
--Q10. What is the revenue contribution of each age group? 
	Select age_group, sum(purchase_amount) as total_revenue
	From customer
	Group By age_group
    Order By total_revenue DESC;